export const USER_API_REQUEST="USER/USER_API_REQUEST"
export const USER_API_SUCCESS="USER/USER_API_SUCCESS"
export const USER_API_FAILED="USER/USER_API_FAILED"

export const EDIT_USER_API_REQUEST="USER/EDIT_USER_API_REQUEST"
export const EDIT_USER_API_SUCCESS="USER/EDIT_USER_API_SUCCESS"
export const EDIT_USER_API_FAILED="USER/EDIT_USER_API_FAILED"